#!/bin/bash

python3 Optimisation.py -s 11 -z [0] -relative True
python3 Optimisation.py -s 11 -z [0] -relative False
python3 Optimisation.py -s 11 -z [1] -relative True
python3 Optimisation.py -s 11 -z [1] -relative False
python3 Optimisation.py -s 11 -z [2] -relative True
python3 Optimisation.py -s 11 -z [2] -relative False
python3 Optimisation.py -s 11 -z [3] -relative True
python3 Optimisation.py -s 11 -z [3] -relative False
python3 Optimisation.py -s 11 -z [4] -relative True
python3 Optimisation.py -s 11 -z [4] -relative False
python3 Optimisation.py -s 11 -z [5] -relative True
python3 Optimisation.py -s 11 -z [5] -relative False
python3 Optimisation.py -s 11 -z [6] -relative True
python3 Optimisation.py -s 11 -z [6] -relative False
python3 Optimisation.py -s 11 -z [7] -relative True
python3 Optimisation.py -s 11 -z [7] -relative False
python3 Optimisation.py -s 11 -z all -relative True
python3 Optimisation.py -s 11 -z all -relative False
python3 Optimisation.py -s 12 -z [0] -relative True
python3 Optimisation.py -s 12 -z [0] -relative False
python3 Optimisation.py -s 13 -z [0] -relative True
python3 Optimisation.py -s 13 -z [0] -relative False
python3 Optimisation.py -s 13 -z [1] -relative True
python3 Optimisation.py -s 13 -z [1] -relative False
python3 Optimisation.py -s 13 -z all -relative True
python3 Optimisation.py -s 13 -z all -relative False
python3 Optimisation.py -s 14 -z [0] -relative True
python3 Optimisation.py -s 14 -z [0] -relative False
python3 Optimisation.py -s 14 -z [1] -relative True
python3 Optimisation.py -s 14 -z [1] -relative False
python3 Optimisation.py -s 14 -z [2] -relative True
python3 Optimisation.py -s 14 -z [2] -relative False
python3 Optimisation.py -s 14 -z [3] -relative True
python3 Optimisation.py -s 14 -z [3] -relative False
python3 Optimisation.py -s 14 -z [4] -relative True
python3 Optimisation.py -s 14 -z [4] -relative False
python3 Optimisation.py -s 14 -z [5] -relative True
python3 Optimisation.py -s 14 -z [5] -relative False
python3 Optimisation.py -s 14 -z [6] -relative True
python3 Optimisation.py -s 14 -z [6] -relative False
python3 Optimisation.py -s 14 -z [7] -relative True
python3 Optimisation.py -s 14 -z [7] -relative False
python3 Optimisation.py -s 14 -z all -relative True
python3 Optimisation.py -s 14 -z all -relative False
python3 Optimisation.py -s 15 -z [0] -relative True
python3 Optimisation.py -s 15 -z [0] -relative False
python3 Optimisation.py -s 15 -z [1] -relative True
python3 Optimisation.py -s 15 -z [1] -relative False
python3 Optimisation.py -s 15 -z [2] -relative True
python3 Optimisation.py -s 15 -z [2] -relative False
python3 Optimisation.py -s 15 -z [3] -relative True
python3 Optimisation.py -s 15 -z [3] -relative False
python3 Optimisation.py -s 15 -z all -relative True
python3 Optimisation.py -s 15 -z all -relative False
python3 Optimisation.py -s 16 -z [0] -relative True
python3 Optimisation.py -s 16 -z [0] -relative False
python3 Optimisation.py -s 16 -z [1] -relative True
python3 Optimisation.py -s 16 -z [1] -relative False
python3 Optimisation.py -s 16 -z [2] -relative True
python3 Optimisation.py -s 16 -z [2] -relative False
python3 Optimisation.py -s 16 -z all -relative True
python3 Optimisation.py -s 16 -z all -relative False
python3 Optimisation.py -s 17 -z [0] -relative True
python3 Optimisation.py -s 17 -z [0] -relative False

